// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// FolderFolders is a Folder of type Folders.
	FolderFolders Folder = iota
	// FolderRoot is a Folder of type Root.
	FolderRoot
	// FolderVersions is a Folder of type Versions.
	FolderVersions
	// FolderLogs is a Folder of type Logs.
	FolderLogs
)

var ErrInvalidFolder = errors.New("not a valid Folder")

const _FolderName = "foldersrootversionslogs"

var _FolderMap = map[Folder]string{
	FolderFolders:  _FolderName[0:7],
	FolderRoot:     _FolderName[7:11],
	FolderVersions: _FolderName[11:19],
	FolderLogs:     _FolderName[19:23],
}

// String implements the Stringer interface.
func (x Folder) String() string {
	if str, ok := _FolderMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Folder(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Folder) IsValid() bool {
	_, ok := _FolderMap[x]
	return ok
}

var _FolderValue = map[string]Folder{
	_FolderName[0:7]:   FolderFolders,
	_FolderName[7:11]:  FolderRoot,
	_FolderName[11:19]: FolderVersions,
	_FolderName[19:23]: FolderLogs,
}

// ParseFolder attempts to convert a string to a Folder.
func ParseFolder(name string) (Folder, error) {
	if x, ok := _FolderValue[name]; ok {
		return x, nil
	}
	return Folder(0), fmt.Errorf("%s is %w", name, ErrInvalidFolder)
}
