// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// HelpsHelp is a Helps of type Help.
	HelpsHelp Helps = iota
	// HelpsCache is a Helps of type Cache.
	HelpsCache
	// HelpsReport is a Helps of type Report.
	HelpsReport
	// HelpsLogs is a Helps of type Logs.
	HelpsLogs
	// HelpsWebsite is a Helps of type Website.
	HelpsWebsite
	// HelpsGithub is a Helps of type Github.
	HelpsGithub
	// HelpsDiscord is a Helps of type Discord.
	HelpsDiscord
	// HelpsPatreon is a Helps of type Patreon.
	HelpsPatreon
	// HelpsAbout is a Helps of type About.
	HelpsAbout
)

var ErrInvalidHelps = errors.New("not a valid Helps")

const _HelpsName = "helpcachereportlogswebsitegithubdiscordpatreonabout"

var _HelpsMap = map[Helps]string{
	HelpsHelp:    _HelpsName[0:4],
	HelpsCache:   _HelpsName[4:9],
	HelpsReport:  _HelpsName[9:15],
	HelpsLogs:    _HelpsName[15:19],
	HelpsWebsite: _HelpsName[19:26],
	HelpsGithub:  _HelpsName[26:32],
	HelpsDiscord: _HelpsName[32:39],
	HelpsPatreon: _HelpsName[39:46],
	HelpsAbout:   _HelpsName[46:51],
}

// String implements the Stringer interface.
func (x Helps) String() string {
	if str, ok := _HelpsMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Helps(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Helps) IsValid() bool {
	_, ok := _HelpsMap[x]
	return ok
}

var _HelpsValue = map[string]Helps{
	_HelpsName[0:4]:   HelpsHelp,
	_HelpsName[4:9]:   HelpsCache,
	_HelpsName[9:15]:  HelpsReport,
	_HelpsName[15:19]: HelpsLogs,
	_HelpsName[19:26]: HelpsWebsite,
	_HelpsName[26:32]: HelpsGithub,
	_HelpsName[32:39]: HelpsDiscord,
	_HelpsName[39:46]: HelpsPatreon,
	_HelpsName[46:51]: HelpsAbout,
}

// ParseHelps attempts to convert a string to a Helps.
func ParseHelps(name string) (Helps, error) {
	if x, ok := _HelpsValue[name]; ok {
		return x, nil
	}
	return Helps(0), fmt.Errorf("%s is %w", name, ErrInvalidHelps)
}
