// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// ListPositionTop is a ListPosition of type Top.
	ListPositionTop ListPosition = iota
	// ListPositionBottom is a ListPosition of type Bottom.
	ListPositionBottom
)

var ErrInvalidListPosition = errors.New("not a valid ListPosition")

const _ListPositionName = "topbottom"

var _ListPositionMap = map[ListPosition]string{
	ListPositionTop:    _ListPositionName[0:3],
	ListPositionBottom: _ListPositionName[3:9],
}

// String implements the Stringer interface.
func (x ListPosition) String() string {
	if str, ok := _ListPositionMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ListPosition(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ListPosition) IsValid() bool {
	_, ok := _ListPositionMap[x]
	return ok
}

var _ListPositionValue = map[string]ListPosition{
	_ListPositionName[0:3]: ListPositionTop,
	_ListPositionName[3:9]: ListPositionBottom,
}

// ParseListPosition attempts to convert a string to a ListPosition.
func ParseListPosition(name string) (ListPosition, error) {
	if x, ok := _ListPositionValue[name]; ok {
		return x, nil
	}
	return ListPosition(0), fmt.Errorf("%s is %w", name, ErrInvalidListPosition)
}
