// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// ModeUnknown is a Mode of type unknown.
	ModeUnknown Mode = ""
	// ModeHome is a Mode of type home.
	ModeHome Mode = "home"
	// ModeSettings is a Mode of type settings.
	ModeSettings Mode = "settings"
	// ModeAbout is a Mode of type about.
	ModeAbout Mode = "about"
	// ModeLogs is a Mode of type logs.
	ModeLogs Mode = "logs"
)

var ErrInvalidMode = errors.New("not a valid Mode")

// String implements the Stringer interface.
func (x Mode) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Mode) IsValid() bool {
	_, err := ParseMode(string(x))
	return err == nil
}

var _ModeValue = map[string]Mode{
	"":         ModeUnknown,
	"home":     ModeHome,
	"settings": ModeSettings,
	"about":    ModeAbout,
	"logs":     ModeLogs,
}

// ParseMode attempts to convert a string to a Mode.
func ParseMode(name string) (Mode, error) {
	if x, ok := _ModeValue[name]; ok {
		return x, nil
	}
	return Mode(""), fmt.Errorf("%s is %w", name, ErrInvalidMode)
}
