// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// PhaseDownload is a Phase of type Download.
	PhaseDownload Phase = iota
	// PhaseExtract is a Phase of type Extract.
	PhaseExtract
	// PhaseDone is a Phase of type Done.
	PhaseDone
	// PhaseError is a Phase of type Error.
	PhaseError
)

var ErrInvalidPhase = errors.New("not a valid Phase")

const _PhaseName = "downloadextractdoneerror"

var _PhaseMap = map[Phase]string{
	PhaseDownload: _PhaseName[0:8],
	PhaseExtract:  _PhaseName[8:15],
	PhaseDone:     _PhaseName[15:19],
	PhaseError:    _PhaseName[19:24],
}

// String implements the Stringer interface.
func (x Phase) String() string {
	if str, ok := _PhaseMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Phase(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Phase) IsValid() bool {
	_, ok := _PhaseMap[x]
	return ok
}

var _PhaseValue = map[string]Phase{
	_PhaseName[0:8]:   PhaseDownload,
	_PhaseName[8:15]:  PhaseExtract,
	_PhaseName[15:19]: PhaseDone,
	_PhaseName[19:24]: PhaseError,
}

// ParsePhase attempts to convert a string to a Phase.
func ParsePhase(name string) (Phase, error) {
	if x, ok := _PhaseValue[name]; ok {
		return x, nil
	}
	return Phase(0), fmt.Errorf("%s is %w", name, ErrInvalidPhase)
}
