// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// SidebarPositionLeft is a SidebarPosition of type Left.
	SidebarPositionLeft SidebarPosition = iota
	// SidebarPositionRight is a SidebarPosition of type Right.
	SidebarPositionRight
)

var ErrInvalidSidebarPosition = errors.New("not a valid SidebarPosition")

const _SidebarPositionName = "leftright"

var _SidebarPositionMap = map[SidebarPosition]string{
	SidebarPositionLeft:  _SidebarPositionName[0:4],
	SidebarPositionRight: _SidebarPositionName[4:9],
}

// String implements the Stringer interface.
func (x SidebarPosition) String() string {
	if str, ok := _SidebarPositionMap[x]; ok {
		return str
	}
	return fmt.Sprintf("SidebarPosition(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SidebarPosition) IsValid() bool {
	_, ok := _SidebarPositionMap[x]
	return ok
}

var _SidebarPositionValue = map[string]SidebarPosition{
	_SidebarPositionName[0:4]: SidebarPositionLeft,
	_SidebarPositionName[4:9]: SidebarPositionRight,
}

// ParseSidebarPosition attempts to convert a string to a SidebarPosition.
func ParseSidebarPosition(name string) (SidebarPosition, error) {
	if x, ok := _SidebarPositionValue[name]; ok {
		return x, nil
	}
	return SidebarPosition(0), fmt.Errorf("%s is %w", name, ErrInvalidSidebarPosition)
}
