// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// FolderFolders is a Folder of type Folders.
	FolderFolders Folder = iota
	// FolderRoot is a Folder of type Root.
	FolderRoot
	// FolderVersions is a Folder of type Versions.
	FolderVersions
	// FolderLogs is a Folder of type Logs.
	FolderLogs
)

var ErrInvalidFolder = errors.New("not a valid Folder")

const _FolderName = "foldersrootversionslogs"

var _FolderMap = map[Folder]string{
	FolderFolders:  _FolderName[0:7],
	FolderRoot:     _FolderName[7:11],
	FolderVersions: _FolderName[11:19],
	FolderLogs:     _FolderName[19:23],
}

// String implements the Stringer interface.
func (x Folder) String() string {
	if str, ok := _FolderMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Folder(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Folder) IsValid() bool {
	_, ok := _FolderMap[x]
	return ok
}

var _FolderValue = map[string]Folder{
	_FolderName[0:7]:   FolderFolders,
	_FolderName[7:11]:  FolderRoot,
	_FolderName[11:19]: FolderVersions,
	_FolderName[19:23]: FolderLogs,
}

// ParseFolder attempts to convert a string to a Folder.
func ParseFolder(name string) (Folder, error) {
	if x, ok := _FolderValue[name]; ok {
		return x, nil
	}
	return Folder(0), fmt.Errorf("%s is %w", name, ErrInvalidFolder)
}

const (
	// HelpsHelp is a Helps of type Help.
	HelpsHelp Helps = iota
	// HelpsCache is a Helps of type Cache.
	HelpsCache
	// HelpsReport is a Helps of type Report.
	HelpsReport
	// HelpsLogs is a Helps of type Logs.
	HelpsLogs
	// HelpsWebsite is a Helps of type Website.
	HelpsWebsite
	// HelpsGithub is a Helps of type Github.
	HelpsGithub
	// HelpsDiscord is a Helps of type Discord.
	HelpsDiscord
	// HelpsPatreon is a Helps of type Patreon.
	HelpsPatreon
	// HelpsAbout is a Helps of type About.
	HelpsAbout
)

var ErrInvalidHelps = errors.New("not a valid Helps")

const _HelpsName = "helpcachereportlogswebsitegithubdiscordpatreonabout"

var _HelpsMap = map[Helps]string{
	HelpsHelp:    _HelpsName[0:4],
	HelpsCache:   _HelpsName[4:9],
	HelpsReport:  _HelpsName[9:15],
	HelpsLogs:    _HelpsName[15:19],
	HelpsWebsite: _HelpsName[19:26],
	HelpsGithub:  _HelpsName[26:32],
	HelpsDiscord: _HelpsName[32:39],
	HelpsPatreon: _HelpsName[39:46],
	HelpsAbout:   _HelpsName[46:51],
}

// String implements the Stringer interface.
func (x Helps) String() string {
	if str, ok := _HelpsMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Helps(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Helps) IsValid() bool {
	_, ok := _HelpsMap[x]
	return ok
}

var _HelpsValue = map[string]Helps{
	_HelpsName[0:4]:   HelpsHelp,
	_HelpsName[4:9]:   HelpsCache,
	_HelpsName[9:15]:  HelpsReport,
	_HelpsName[15:19]: HelpsLogs,
	_HelpsName[19:26]: HelpsWebsite,
	_HelpsName[26:32]: HelpsGithub,
	_HelpsName[32:39]: HelpsDiscord,
	_HelpsName[39:46]: HelpsPatreon,
	_HelpsName[46:51]: HelpsAbout,
}

// ParseHelps attempts to convert a string to a Helps.
func ParseHelps(name string) (Helps, error) {
	if x, ok := _HelpsValue[name]; ok {
		return x, nil
	}
	return Helps(0), fmt.Errorf("%s is %w", name, ErrInvalidHelps)
}

const (
	// ListPositionTop is a ListPosition of type Top.
	ListPositionTop ListPosition = iota
	// ListPositionBottom is a ListPosition of type Bottom.
	ListPositionBottom
)

var ErrInvalidListPosition = errors.New("not a valid ListPosition")

const _ListPositionName = "topbottom"

var _ListPositionMap = map[ListPosition]string{
	ListPositionTop:    _ListPositionName[0:3],
	ListPositionBottom: _ListPositionName[3:9],
}

// String implements the Stringer interface.
func (x ListPosition) String() string {
	if str, ok := _ListPositionMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ListPosition(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ListPosition) IsValid() bool {
	_, ok := _ListPositionMap[x]
	return ok
}

var _ListPositionValue = map[string]ListPosition{
	_ListPositionName[0:3]: ListPositionTop,
	_ListPositionName[3:9]: ListPositionBottom,
}

// ParseListPosition attempts to convert a string to a ListPosition.
func ParseListPosition(name string) (ListPosition, error) {
	if x, ok := _ListPositionValue[name]; ok {
		return x, nil
	}
	return ListPosition(0), fmt.Errorf("%s is %w", name, ErrInvalidListPosition)
}

const (
	// ModeUnknown is a Mode of type unknown.
	ModeUnknown Mode = ""
	// ModeHome is a Mode of type home.
	ModeHome Mode = "home"
	// ModeSettings is a Mode of type settings.
	ModeSettings Mode = "settings"
	// ModeAbout is a Mode of type about.
	ModeAbout Mode = "about"
	// ModeLogs is a Mode of type logs.
	ModeLogs Mode = "logs"
)

var ErrInvalidMode = errors.New("not a valid Mode")

// String implements the Stringer interface.
func (x Mode) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Mode) IsValid() bool {
	_, err := ParseMode(string(x))
	return err == nil
}

var _ModeValue = map[string]Mode{
	"":         ModeUnknown,
	"home":     ModeHome,
	"settings": ModeSettings,
	"about":    ModeAbout,
	"logs":     ModeLogs,
}

// ParseMode attempts to convert a string to a Mode.
func ParseMode(name string) (Mode, error) {
	if x, ok := _ModeValue[name]; ok {
		return x, nil
	}
	return Mode(""), fmt.Errorf("%s is %w", name, ErrInvalidMode)
}

const (
	// PhaseDownload is a Phase of type Download.
	PhaseDownload Phase = iota
	// PhaseExtract is a Phase of type Extract.
	PhaseExtract
	// PhaseDone is a Phase of type Done.
	PhaseDone
	// PhaseError is a Phase of type Error.
	PhaseError
)

var ErrInvalidPhase = errors.New("not a valid Phase")

const _PhaseName = "downloadextractdoneerror"

var _PhaseMap = map[Phase]string{
	PhaseDownload: _PhaseName[0:8],
	PhaseExtract:  _PhaseName[8:15],
	PhaseDone:     _PhaseName[15:19],
	PhaseError:    _PhaseName[19:24],
}

// String implements the Stringer interface.
func (x Phase) String() string {
	if str, ok := _PhaseMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Phase(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Phase) IsValid() bool {
	_, ok := _PhaseMap[x]
	return ok
}

var _PhaseValue = map[string]Phase{
	_PhaseName[0:8]:   PhaseDownload,
	_PhaseName[8:15]:  PhaseExtract,
	_PhaseName[15:19]: PhaseDone,
	_PhaseName[19:24]: PhaseError,
}

// ParsePhase attempts to convert a string to a Phase.
func ParsePhase(name string) (Phase, error) {
	if x, ok := _PhaseValue[name]; ok {
		return x, nil
	}
	return Phase(0), fmt.Errorf("%s is %w", name, ErrInvalidPhase)
}

const (
	// SidebarPositionLeft is a SidebarPosition of type Left.
	SidebarPositionLeft SidebarPosition = iota
	// SidebarPositionRight is a SidebarPosition of type Right.
	SidebarPositionRight
)

var ErrInvalidSidebarPosition = errors.New("not a valid SidebarPosition")

const _SidebarPositionName = "leftright"

var _SidebarPositionMap = map[SidebarPosition]string{
	SidebarPositionLeft:  _SidebarPositionName[0:4],
	SidebarPositionRight: _SidebarPositionName[4:9],
}

// String implements the Stringer interface.
func (x SidebarPosition) String() string {
	if str, ok := _SidebarPositionMap[x]; ok {
		return str
	}
	return fmt.Sprintf("SidebarPosition(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SidebarPosition) IsValid() bool {
	_, ok := _SidebarPositionMap[x]
	return ok
}

var _SidebarPositionValue = map[string]SidebarPosition{
	_SidebarPositionName[0:4]: SidebarPositionLeft,
	_SidebarPositionName[4:9]: SidebarPositionRight,
}

// ParseSidebarPosition attempts to convert a string to a SidebarPosition.
func ParseSidebarPosition(name string) (SidebarPosition, error) {
	if x, ok := _SidebarPositionValue[name]; ok {
		return x, nil
	}
	return SidebarPosition(0), fmt.Errorf("%s is %w", name, ErrInvalidSidebarPosition)
}
