[common]
open = "Open"
close = "Close"

[topbar]
install = "Install version"
folders = "Folders"
settings = "Settings"
help = "Help"

[topbar.dl]
webview = "Select a release asset"
selecting = "Selecting..."
downloading = "Downloading..."
connecting = "Connecting..."
extracting = "Extracting..."
extracting_files = "Extracting files: %d / %d"
extracted_count = "Extracted %d files..."
done = "Done!"
install_complete = "Installation complete."
failed = "Failed"

[topbar.f]
root = "Launcher Root"
versions = "Versions"
logs = "Logs"

[topbar.h]
cache = "Clear cache"
report = "Report a Bug or Suggest a Feature"
view = "View logs"
website = "Website"
about = "About"

[home]
title     = "Installed versions"
no_versions = "No versions installed. Use the Install button to download one."
launch   = "Launch"
kill     = "Kill"
folder   = "Open Folder"
delete   = "Delete"
shortcut = "Create Shortcut"

[settings]
color_mode = "Color mode"
color_mode_auto = "Auto"
color_mode_light = "Light"
color_mode_dark = "Dark"
language = "Language"
translate = "Translate changelog - Google Translate"
scale = "Scale"
music = "Disable background music"

[about]
title = "About"
content = "A Launcher developed for Project-86-Community-Game for managing game files."
lead = "Taliayaya - Lead Developer"
dev = "realskyquest - Launcher Developer"
license = """Background music: "Project: 86 OST: Legion" by XYETRY.

 Project-86-Launcher: A Launcher developed for Project-86-Community-Game for managing game files.
 Copyright (C) 2025 Project 86 Community

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>."""

[logs]
title = "Latest Log"
error = "Could not read log file."
